image: atlassian/default-image:4

definitions:
  steps:
    - step: &run-CI-checks
        name: Run CI checks
        services:
          - docker
        caches:
          - docker
        script:
          - docker build -f Dockerfile.test .

pipelines:
  branches:
    "main":
      - step: *run-CI-checks
      - step:
          name: Build and Publish Docker Image
          services:
            - docker
          caches:
            - docker
          script:
            - export IMAGE_NAME="iternio/valhalla-debug"
            - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            - docker build -t "$IMAGE_NAME:$BITBUCKET_COMMIT" .
            - docker tag "$IMAGE_NAME:$BITBUCKET_COMMIT" "$IMAGE_NAME:latest"
            - docker push "$IMAGE_NAME:$BITBUCKET_COMMIT" "$IMAGE_NAME:latest"

  pull-requests:
    "**":
      - step: *run-CI-checks
