[package]
name = "valhalla-debug"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = "thin"

[dependencies]
axum = "0.7"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "fs"] }
tracing = "0.1"
tracing-subscriber = "0.3"
