[package]
name = "valhalla-debug"
description = "Debug tool for Valhalla routing engine"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["kinkard"]
repository = "https://github.com/kinkard/valhalla-debug"

[profile.release]
strip = true
lto = "thin"

[dependencies]
axum = "0.7"
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "fs"] }
tracing = "0.1"
tracing-subscriber = "0.3"
